#!/bin/sh
# Spam Samy when the time feels right

N=$1
if [ -z $N ]; then
    N=1
fi

for i in `seq $N`; do
    SAMY='\<@!347711466167861248\>'
    ssh vps -q -t http -q localhost:7010/send/channel id=$CHGROUPEDES4 message="$SAMY\ est\ moche"
done
